// Code generated by genmark. DO NOT EDIT.
package sqlast

type AlterTableAction interface {
	alterTableActionMarker()
	ASTNode
}
type alterTableAction struct{}

func (alterTableAction) alterTableActionMarker() {}
