// Code generated by genmark. DO NOT EDIT.
package sqlast

type AlterColumnAction interface {
	alterColumnActionMarker()
	Node
}
type alterColumnAction struct{}

func (alterColumnAction) alterColumnActionMarker() {}
