package sqlast

// Code generated by genmark. DO NOT EDIT.

type AlterColumnAction interface {
	alterColumnActionMarker()
	Node
}
type alterColumnAction struct{}

func (alterColumnAction) alterColumnActionMarker() {}
