package sqlast

// Code generated by genmark. DO NOT EDIT.

type AlterTableAction interface {
	alterTableActionMarker()
	Node
}
type alterTableAction struct{}

func (alterTableAction) alterTableActionMarker() {}
