package sqlast

// Code generated by genmark. DO NOT EDIT.

type MyDataTypeDecoration interface {
	myDataTypeDecorationMarker()
	Node
}
type myDataTypeDecoration struct{}

func (myDataTypeDecoration) myDataTypeDecorationMarker() {}
