// Code generated by genmark. DO NOT EDIT.
package sqlast

type MyDataTypeDecoration interface {
	myDataTypeDecorationMarker()
	Node
}
type myDataTypeDecoration struct{}

func (myDataTypeDecoration) myDataTypeDecorationMarker() {}
