// Code generated by genmark. DO NOT EDIT.
package sqlast

type SQLSetOperator interface {
	sqlSetOperatorMarker()
	ASTNode
}
type sqlSetOperator struct{}

func (sqlSetOperator) sqlSetOperatorMarker() {}
