package sqlast

// Code generated by genmark. DO NOT EDIT.

type SQLSetOperator interface {
	sqlSetOperatorMarker()
	Node
}
type sqlSetOperator struct{}

func (sqlSetOperator) sqlSetOperatorMarker() {}
