package sqlast

// Code generated by genmark. DO NOT EDIT.

type SQLWindowFrameBound interface {
	sqlWindowFrameBoundMarker()
	Node
}
type sqlWindowFrameBound struct{}

func (sqlWindowFrameBound) sqlWindowFrameBoundMarker() {}
