// Code generated by genmark. DO NOT EDIT.
package sqlast

type SQLWindowFrameBound interface {
	sqlWindowFrameBoundMarker()
	Node
}
type sqlWindowFrameBound struct{}

func (sqlWindowFrameBound) sqlWindowFrameBoundMarker() {}
