// Code generated by genmark. DO NOT EDIT.
package sqlast

type SQLSetOperator interface {
	sqlSetOperatorMarker()
	Node
}
type sqlSetOperator struct{}

func (sqlSetOperator) sqlSetOperatorMarker() {}
