// Code generated by genmark. DO NOT EDIT.
package sqlast

type TableReference interface {
	tableReferenceMarker()
	Node
}
type tableReference struct{}

func (tableReference) tableReferenceMarker() {}
