// Code generated by genmark. DO NOT EDIT.
package sqlast

type TableConstraintSpec interface {
	tableConstraintSpecMarker()
	ASTNode
}
type tableConstraintSpec struct{}

func (tableConstraintSpec) tableConstraintSpecMarker() {}
