package sqlast

// Code generated by genmark. DO NOT EDIT.

type TableReference interface {
	tableReferenceMarker()
	Node
}
type tableReference struct{}

func (tableReference) tableReferenceMarker() {}
