package sqlast

// Code generated by genmark. DO NOT EDIT.

type TableConstraintSpec interface {
	tableConstraintSpecMarker()
	Node
}
type tableConstraintSpec struct{}

func (tableConstraintSpec) tableConstraintSpecMarker() {}
